# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run: npm uninstall node-sass
      - run: npm install node-sass
      - run:
          name: "Install node modules"
          command: npm i
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: "Linting the project"
          command: npm run lint

  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - run:
          name: "Test Project"
          command: npm run test

  analyze:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - restore_cache:
            key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: "Audit Project"
          command: npm audit
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
